-- Consulta 1
SELECT 
    C2.NOME, 
    E.*
FROM CLIENTE C1
    JOIN CLIENTE C2 ON C1.CLIENTE_INDICA = C2.CODIGO
    JOIN ENDERECO E ON C2.CODIGO_ENDERECO = E.CODIGO
WHERE 
    C1.NOME = 'Ana Beatriz' 
    AND C1.SOBRENOME = 'Oliveira';

-- Consulta 2
SELECT 
    F.NOME
FROM
    FORNECEDOR F
    JOIN FORNECEDOR_FORNECE_PRODUTO FFP ON F.CODIGO = FFP.CODIGO_FORNECEDOR
GROUP BY F.CODIGO, F.NOME
HAVING COUNT(*) >= ALL
    (SELECT COUNT(*) FROM FORNECEDOR_FORNECE_PRODUTO GROUP BY CODIGO_FORNECEDOR);

-- Consulta 3
SELECT DISTINCT
    C.NOME
FROM
    CLIENTE C JOIN ORDEM_DE_COMPRA OC ON C.CODIGO = OC.CODIGO_CLIENTE
WHERE
    OC.DATA_COMPRA BETWEEN DATE '2022-01-01' AND DATE '2022-12-31' AND
    OC.DESCONTO > 60;

-- Consulta 4
SELECT
    C2.CODIGO
FROM
    CLIENTE C1
    JOIN CLIENTE C2 ON C1.CODIGO = C2.CLIENTE_INDICA
    JOIN ORDEM_DE_COMPRA OC ON C2.CODIGO = OC.CODIGO_CLIENTE
WHERE
    C1.NOME = 'Maria Helena' AND C1.SOBRENOME = 'Silva' AND
    C2.DATA_INDICACAO < DATE '2025-01-01';

-- Consulta 5
SELECT CODIGO, NOME
FROM PRODUTO
WHERE ABS(DATA_VALIDADE - DATA_FABRICACAO) > 365;

-- Consulta 6
WITH QUERY_COMPRAS AS (
    SELECT
        OC.CODIGO,
        NF.VALOR_TOTAL
    FROM
        CLIENTE C
        JOIN ENDERECO E ON C.CODIGO_ENDERECO = E.CODIGO
        JOIN ORDEM_DE_COMPRA OC ON C.CODIGO = OC.CODIGO_CLIENTE
        JOIN NOTA_FISCAL NF ON OC.CODIGO_NOTA_FISCAL = NF.CODIGO
    WHERE
        C.DATA_NASCIMENTO BETWEEN DATE '1980-01-01' AND DATE '1989-12-31'
        AND E.CIDADE = 'Campina Grande')
SELECT CODIGO
FROM QUERY_COMPRAS
WHERE VALOR_TOTAL = (SELECT MIN(VALOR_TOTAL) FROM QUERY_COMPRAS);

-- Consulta 7
SELECT
    NF.NUMERO, P.NOME, CP.QUANTIDADE, NF.VALOR_TOTAL
FROM
    COMPRA_POSSUI_PRODUTO CP
    JOIN ORDEM_DE_COMPRA OC ON OC.CODIGO = CP.CODIGO_COMPRA
    JOIN NOTA_FISCAL NF ON NF.CODIGO = OC.CODIGO_NOTA_FISCAL
    JOIN PRODUTO P ON CP.CODIGO_PRODUTO = P.CODIGO
WHERE
    CP.QUANTIDADE = (
        SELECT MAX(CP2.QUANTIDADE)
        FROM COMPRA_POSSUI_PRODUTO CP2
        WHERE CP2.CODIGO_COMPRA = CP.CODIGO_COMPRA)
AND CP.QUANTIDADE > 5;

-- Consulta 8
SELECT
    C.CODIGO, C.NOME
FROM
    CLIENTE C
    JOIN ORDEM_DE_COMPRA OC ON C.CODIGO = OC.CODIGO_CLIENTE
    JOIN EMAIL E ON C.CODIGO = E.CODIGO_CLIENTE
WHERE
    OC.STATUS = 'FINALIZADA' AND
    E.CLIENTE_ABRIU = 'SIM';

-- Consulta 9
SELECT
    OC.CODIGO,
    NF.VALOR_TOTAL,
    CASE 
        WHEN NF.VALOR_TOTAL > 1000 THEN 'ALTA'
        WHEN NF.VALOR_TOTAL BETWEEN 500 AND 1000 THEN 'MÉDIA'
        ELSE 'BAIXA'
    END AS CATEGORIA
FROM
    ORDEM_DE_COMPRA OC
    JOIN NOTA_FISCAL NF ON OC.CODIGO_NOTA_FISCAL = NF.CODIGO;

-- Consulta 10
SELECT
    C.NOME, CA.CODIGO, COUNT(CA.CODIGO_CUPOM) AS TOTAL_CUPOM, SUM(CD.DESCONTO) AS TOTAL_DESCONTO
FROM
    CLIENTE C
    JOIN CARRINHO CA ON C.CODIGO = CA.CODIGO_CLIENTE
    JOIN CUPOM_DE_DESCONTO CD ON CA.CODIGO_CUPOM = CD.CODIGO
GROUP BY CA.CODIGO, C.NOME
ORDER BY TOTAL_DESCONTO;