CREATE TABLE ENDERECO (
    CODIGO INT,
    RUA VARCHAR(255) NOT NULL,
    NUMERO VARCHAR(255) NOT NULL,
    BAIRRO VARCHAR(100) NOT NULL,
    CIDADE VARCHAR(100) NOT NULL,
    ESTADO VARCHAR(50) NOT NULL,
    CEP VARCHAR(10) NOT NULL,
    CONSTRAINT PK_ENDERECO PRIMARY KEY(CODIGO)
);

CREATE TABLE CLIENTE (
    CODIGO INT,
    NOME VARCHAR(100) NOT NULL,
    SOBRENOME VARCHAR(100) NOT NULL,
    DT_NASCIMENTO DATE,
    SEXO CHAR(1),
    COD_ENDERECO INT NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PONTOS INT,
    INDICADO_POR INT,
    DT_INDICACAO DATE,
    CONSTRAINT PK_CLIENTE PRIMARY KEY(CODIGO),
    CONSTRAINT CHECK_CLIENTE_SEXO CHECK (SEXO IN ('M', 'F', 'O')),
    CONSTRAINT CHECK_CLIENTE_PONTOS_POSITIVOS CHECK (PONTOS >= 0),
    CONSTRAINT FK_CLIENTE_ENDERECO FOREIGN KEY (COD_ENDERECO) REFERENCES ENDERECO(CODIGO),
    CONSTRAINT FK_CLIENTE_CLIENTE FOREIGN KEY (INDICADO_POR) REFERENCES CLIENTE(CODIGO) ON DELETE SET NULL
);

-- TELEFONES DE CLIENTE
CREATE TABLE TELEFONE_CLIENTE (
    COD_CLIENTE INT,
    NUMERO VARCHAR(15),
    CONSTRAINT PK_TELEFONE PRIMARY KEY (COD_CLIENTE, NUMERO),
    CONSTRAINT FK_TELEFONE_CLIENTE FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE(CODIGO) ON DELETE CASCADE
);

-- EMAILS DE CLIENTE
CREATE TABLE EMAIL_CLIENTE (
    CODIGO INT,
    CONTEUDO CLOB NOT NULL,
    DT_ENVIO DATE NOT NULL,
    ASSUNTO VARCHAR(100) NOT NULL,
    COD_CLIENTE INT NOT NULL,
    CLICOU_CONTEUDO CHAR(1),
    ABRIU CHAR(1),
    CONSTRAINT PK_EMAIL PRIMARY KEY(CODIGO),
    CONSTRAINT FK_EMAIL_CLIENTE FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE(CODIGO) ON DELETE CASCADE
);

CREATE TABLE FORNECEDOR (
    CODIGO INT,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    COD_ENDERECO INT NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    HOME_PAGE VARCHAR(50) NOT NULL,
    CONSTRAINT PK_FORNECEDOR PRIMARY KEY(CODIGO),
    CONSTRAINT FK_FORNECEDOR_ENDERECO FOREIGN KEY (COD_ENDERECO) REFERENCES ENDERECO(CODIGO)
);

CREATE TABLE CATEGORIA (
    CODIGO INT,
    NOME VARCHAR(100) NOT NULL,
    CONSTRAINT PK_CATEGORIA PRIMARY KEY(CODIGO)
);

CREATE TABLE PRODUTO (
    CODIGO INT,
    NOME VARCHAR(100) NOT NULL,
    PRECO NUMERIC(10,2) NOT NULL,
    DESCRICAO VARCHAR(100),
    ESPECIFICACAO VARCHAR(255),
    DT_FABRICACAO DATE,
    DT_VALIDADE DATE,
    COD_CATEGORIA INT NOT NULL,
    CONSTRAINT PK_PRODUTO PRIMARY KEY(CODIGO),
    CONSTRAINT CHECK_PRODUTO_PRECO_POSITIVO CHECK (PRECO >= 0),
    CONSTRAINT FK_PRODUTO_CATEGORIA FOREIGN KEY (COD_CATEGORIA) REFERENCES CATEGORIA(CODIGO)
);

-- FOTOS DE PRODUTO
CREATE TABLE FOTO_PRODUTO (
    CODIGO INT,
    COD_PRODUTO INT NOT NULL,
    FOTO BLOB,
    CONSTRAINT PK_FOTO_PRODUTO PRIMARY KEY(CODIGO),
    CONSTRAINT FK_FOTO_PRODUTO FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO(CODIGO) ON DELETE CASCADE
);

CREATE TABLE FORNECIDO_POR (
    COD_FORNECEDOR INT,
    COD_PRODUTO INT,
    CONSTRAINT PK_FORNECIDO_POR PRIMARY KEY(COD_FORNECEDOR, COD_PRODUTO),
    CONSTRAINT FK_FORNECIDO_POR_FORNECEDOR FOREIGN KEY (COD_FORNECEDOR) REFERENCES FORNECEDOR(CODIGO) ON DELETE CASCADE,
    CONSTRAINT FK_FORNECIDO_POR_PRODUTO FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO(CODIGO) ON DELETE CASCADE
);

CREATE TABLE CENTRO_DISTRIBUICAO (
    CODIGO INT,
    NOME VARCHAR(100) NOT NULL,
    COD_ENDERECO INT NOT NULL,
    CONSTRAINT PK_CENTRO_DISTRIBUICAO PRIMARY KEY(CODIGO),
    CONSTRAINT FK_CENTRO_DISTRIBUICAO_ENDERECO FOREIGN KEY (COD_ENDERECO) REFERENCES ENDERECO(CODIGO)
);

CREATE TABLE ITEM_INVENTARIO (
    COD_CENTRO_DISTRIBUICAO INT,
    COD_PRODUTO INT,
    QUANTIDADE INT NOT NULL,
    CONSTRAINT PK_ITEM_INVENTARIO PRIMARY KEY(COD_CENTRO_DISTRIBUICAO, COD_PRODUTO),
    CONSTRAINT FK_ITEM_INVENTARIO_CENTRO_DISTRIBUICAO FOREIGN KEY (COD_CENTRO_DISTRIBUICAO) REFERENCES CENTRO_DISTRIBUICAO(CODIGO) ON DELETE CASCADE,
    CONSTRAINT FK_ITEM_INVENTARIO_PRODUTO FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO(CODIGO) ON DELETE CASCADE
);

CREATE TABLE CARRINHO (
    CODIGO INT,
    COD_CLIENTE INT NOT NULL,
    CONSTRAINT PK_CARRINHO PRIMARY KEY(CODIGO),
    CONSTRAINT FK_CARRINHO_CLIENTE FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE(CODIGO) ON DELETE CASCADE
);

-- CARRINHO POSSUI PRODUTO
CREATE TABLE POSSUI (
    COD_CARRINHO INT,
    COD_PRODUTO INT,
    QUANTIDADE INT NOT NULL,
    CONSTRAINT PK_POSSUI PRIMARY KEY(COD_CARRINHO, COD_PRODUTO),
    CONSTRAINT FK_POSSUI_CARRINHO FOREIGN KEY (COD_CARRINHO) REFERENCES CARRINHO(CODIGO) ON DELETE CASCADE,
    CONSTRAINT FK_POSSUI_PRODUTO FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO(CODIGO) ON DELETE CASCADE
);

CREATE TABLE CUPOM_DESCONTO (
    CODIGO INT,
    DESCONTO NUMERIC(6,4) NOT NULL,
    COD_CARRINHO INT,
    CONSTRAINT PK_CUPOM_DESCONTO PRIMARY KEY(CODIGO),
    CONSTRAINT CHECK_CUPOM_DESCONTO_DESCONTO_POSITIVO CHECK (DESCONTO >= 0),
    CONSTRAINT FK_CUPOM_DESCONTO_CARRINHO FOREIGN KEY (COD_CARRINHO) REFERENCES CARRINHO(CODIGO) ON DELETE SET NULL
);

CREATE TABLE RESTRITO (
    COD_CUPOM_DESCONTO INT,
    COD_CATEGORIA INT,
    CONSTRAINT PK_RESTRITO PRIMARY KEY(COD_CUPOM_DESCONTO, COD_CATEGORIA),
    CONSTRAINT FK_RESTRITO_CUPOM_DESCONTO FOREIGN KEY (COD_CUPOM_DESCONTO) REFERENCES CUPOM_DESCONTO(CODIGO) ON DELETE CASCADE,
    CONSTRAINT FK_RESTRITO_CATEGORIA FOREIGN KEY (COD_CATEGORIA) REFERENCES CATEGORIA(CODIGO) ON DELETE CASCADE
);

CREATE TABLE TRANSPORTADORA (
    CODIGO INT,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    URL VARCHAR(255) NOT NULL,
    COD_ENDERECO INT NOT NULL,
    CONSTRAINT PK_TRANSPORTADORA PRIMARY KEY(CODIGO),
    CONSTRAINT FK_TRANSPORTADORA_ENDERECO FOREIGN KEY (COD_ENDERECO) REFERENCES ENDERECO(CODIGO)
);

CREATE TABLE ORDEM_COMPRA (
    CODIGO INT,
    DT_PEDIDO DATE NOT NULL,
    STATUS VARCHAR(25),
    COD_ENDERECO INT NOT NULL,
    VL_FRETE NUMERIC(10,2),
    DESCONTO NUMERIC(6,4),
    COD_CLIENTE INT NOT NULL,
    COD_TRANSPORTADORA INT NOT NULL,
    CONSTRAINT PK_ORDEM_COMPRA PRIMARY KEY(CODIGO),
    CONSTRAINT CHECK_ORDEM_COMPRA_STATUS CHECK (STATUS IN ('Aguardando Pagamento', 'Em separação', 'Em transporte', 'Finalizada')),
    CONSTRAINT CHECK_ORDEM_COMPRA_VL_FRETE_POSITIVO CHECK (VL_FRETE >= 0),
    CONSTRAINT CHECK_ORDEM_COMPRA_DESCONTO_POSITIVO CHECK (DESCONTO >= 0),
    CONSTRAINT FK_ORDEM_COMPRA_CLIENTE FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE(CODIGO),
    CONSTRAINT FK_ORDEM_COMPRA_TRANSPORTADORA FOREIGN KEY (COD_TRANSPORTADORA) REFERENCES TRANSPORTADORA(CODIGO)
);

CREATE TABLE NOTA_FISCAL (
    CODIGO INT,
    COD_ORDEM_COMPRA INT NOT NULL,
    CHAVE_ACESSO VARCHAR(100) NOT NULL,
    INSCRICAO_ESTADUAL VARCHAR(50) NOT NULL,
    VL_TOTAL NUMERIC(10,2) NOT NULL,
    VL_FRETE NUMERIC(10,2),
    SERIE VARCHAR(20) NOT NULL,
    NUMERO VARCHAR(50) NOT NULL,
    CONSTRAINT PK_NOTA_FISCAL PRIMARY KEY(CODIGO),
    CONSTRAINT CHECK_NOTA_FISCAL_VL_TOTAL_POSITIVO CHECK (VL_TOTAL >= 0),
    CONSTRAINT CHECK_NOTA_FISCAL_VL_FRETE_POSITIVO CHECK (VL_FRETE >= 0),
    CONSTRAINT FK_NOTA_FISCAL_ORDEM_COMPRA FOREIGN KEY (COD_ORDEM_COMPRA) REFERENCES ORDEM_COMPRA(CODIGO) ON DELETE CASCADE
);

CREATE TABLE EH_AVALIADO (
    COD_PRODUTO INT,
    COD_ORDEM_COMPRA INT,
    DESCRICAO VARCHAR(100),
    NOTA INT,
    CONSTRAINT PK_EH_AVALIADO PRIMARY KEY(COD_PRODUTO, COD_ORDEM_COMPRA),
    CONSTRAINT CHECK_EH_AVALIADO_NOTA CHECK (NOTA IN (1, 2, 3, 4, 5)),
    CONSTRAINT FK_EH_AVALIADO_PRODUTO FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO(CODIGO) ON DELETE CASCADE,
    CONSTRAINT FK_EH_AVALIADO_ORDEM_COMPRA FOREIGN KEY (COD_ORDEM_COMPRA) REFERENCES ORDEM_COMPRA(CODIGO) ON DELETE CASCADE
);

-- PRODUTO PERTENCE A ORDEM DE COMPRA
CREATE TABLE PERTENCE (
    COD_PRODUTO INT,
    COD_ORDEM_COMPRA INT,
    QUANTIDADE INT NOT NULL,
    VL_ATUAL NUMERIC(10,2) NOT NULL,
    CONSTRAINT PK_PERTENCE PRIMARY KEY(COD_PRODUTO, COD_ORDEM_COMPRA),
    CONSTRAINT CHECK_PERTENCE_QUANTIDADE_POSITIVA CHECK (QUANTIDADE >= 0),
    CONSTRAINT CHECK_PERTENCE_VL_ATUAL_POSITIVO  CHECK (VL_ATUAL >= 0),
    CONSTRAINT FK_PERTENCE_PRODUTO FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO(CODIGO) ON DELETE CASCADE,
    CONSTRAINT FK_PERTENCE_ORDEM_COMPRA FOREIGN KEY (COD_ORDEM_COMPRA) REFERENCES ORDEM_COMPRA(CODIGO) ON DELETE CASCADE
);

CREATE TABLE HISTORICO (
    CODIGO INT,
    DT_VISUALIZACAO DATE NOT NULL, 
    COD_CLIENTE INT NOT NULL,
    COD_PRODUTO INT NOT NULL,
    CONSTRAINT PK_HISTORICO PRIMARY KEY (CODIGO),
    CONSTRAINT FK_HISTORICO_CLIENTE FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE(CODIGO),
    CONSTRAINT FK_HISTORICO_PRODUTO FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO(CODIGO)
);

CREATE TABLE ADICAO_PRODUTO_CARRINHO (
    COD_HISTORICO INT,
    FINALIZOU CHAR(1) DEFAULT ('N'),
    CONSTRAINT PK_ADICAO_PRODUTO_CARRINHO PRIMARY KEY (COD_HISTORICO),
    CONSTRAINT CHECK_ADICAO_PRODUTO_CARRINHO_FINALIZOU CHECK (FINALIZOU IN ('S', 'N')),
    CONSTRAINT FK_ADICAO_PRODUTO_CARRINHO_HISTORICO FOREIGN KEY (COD_HISTORICO) REFERENCES HISTORICO(CODIGO) ON DELETE CASCADE
);

CREATE TABLE VISUALIZACAO_PRODUTO (
    COD_HISTORICO INT,
    TEMPO TIMESTAMP NOT NULL,
    CONSTRAINT PK_VISUALIZACAO_PRODUTO PRIMARY KEY (COD_HISTORICO),
    CONSTRAINT FK_VISUALIZACAO_PRODUTO_HISTORICO FOREIGN KEY (COD_HISTORICO) REFERENCES HISTORICO(CODIGO) ON DELETE CASCADE
);